# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'

# google-filament
#source 'https://github.com/google/filament.git'

platform :ios, '12.4'
  inhibit_all_warnings!
  install! 'cocoapods',
    :warn_for_unused_master_specs_repo => false


def libs_Filament
  pod 'Filament', '~> 1.51.6'
    #:podspec => 'https://github.com/google/filament/blob/main/ios/CocoaPods/Filament.podspec'
    #:subspecs => ['filament', 'camutils', 'gltfio_core', 'math', 'utils', 'viewer', 'ktxreader']
    #:source => 'google-filament-releases-download-v1.51.4-filament-v1.51.4-ios.tgz'
    #:git => 'https://github.com/google/filament.git', :tag => 'v1.51.4'
end

target 'OCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCDemo
  libs_Filament
  
end
